name: Starcharts

on:
  schedule:
    - cron: "0 0/12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Generate starcharts
    runs-on: ubuntu-latest
    steps:
      - uses: MaoLongLong/actions-starcharts@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_path: images/starcharts.svg
          commit_message: "chore: update starcharts to leetcode project @doocs"
          stars_change: "100"
